### ISSUE TITLE
Add licence?

### ISSUE THREAD

**Issue by alexgloverl** [bellecp/fast-p#1]
This is a really interesting approach to dealing with masses of PDFs!

Sorry to be *that* guy, but would you consider adding whatever is your favourite open source license? (If not, then please don't worry!)

Both the idea and the actual script/bash function most probably cross the threshold for copyrightability.

Thanks and sorry again!

**Comment by bellecp** [comment]
Fixed (MIT)

**Comment by alexgloverl** [comment]
Thanks a lot! :)
