### ISSUE TITLE
Put fast-p_cached_pdftotext_output.db in $XDG_CACHE_HOME/

### ISSUE THREAD

**Issue by DamienRobert** [bellecp/fast-p#12]
Since this is a cache file, it would be better to put it in ~/.cache (ake $XDG_CACHE_HOME) rather than directly in $HOME.

**Comment by bellecp** [comment]
Thanks! Fixed in 0.2.4.

**Comment by DamienRobert** [comment]
Thanks for the quick fix (just tested the new version!)
