### ISSUE TITLE
Feature request: Open pdf in a detached process

### ISSUE THREAD

**Issue by BonaBeavis** [bellecp/fast-p#14]
Hello,

unfortunately my command line fu is not advanced enough to modify the startup script myself.
What I would like is that after pressing return the selected pdf is opened but the fast-p terminal stays unchanged. So I could change my search and open another pdf from the same terminal.

**Comment by bellecp** [comment]
What is your current bashrc definition of the command ``p``?

**Comment by BonaBeavis** [comment]
I tried several combination of `xargs`, `nohup` and `&` with no success. 
```
p () {
  open=xdg-open   # this will open pdf file withthe default PDF viewer on KDE, xfce, LXDE and perhaps on other desktops.
  i3-msg layout tabbed > /dev/null 2> /dev/null
  rg --files -g "*.{pdf}"  \
    | fast-p \
    | fzf --read0 --reverse -e -d $'\t'  \
    --height 100% --preview-window up --preview '
  v=$(echo {q} | tr " " "|");
  echo -e {1}"\n"{2} | grep -E "^|$v" -i --color=always;
  ' \
    | cut -z -f 1 -d $'\t' | tr -d '\n' | xargs -r --null $open > /dev/null 2> /dev/null
  p # keep fast-p open
}
```

**Comment by bellecp** [comment]
You may have some luck with the ``-m`` option of fzf that lets you send multiples entries (each selected with tab).  However, you would have to completely change the command following fzf to parse the multiple entries from fzf.

Launching ``p`` is supposed to be very fast thanks to the cache, you may simply type ``p`` again in the terminal.

**Comment by bellecp** [comment]
Closing this since the desired custom behavior can be achieved by tweaking .bashrc.

**Comment by C0D3D3V** [comment]
Just for the record. This works:
```
pdf() {
    open=xdg-open   # this will open pdf file withthe default PDF viewer on KDE, xfce, LXDE and perhaps on other desktops.

    ag -U -g ".pdf$" \
    | fast-p \
    | fzf --read0 --reverse -e -d $'\t'  \
        --preview-window down:80% --preview '
            v=$(echo {q} | tr " " "|");
            echo -e {1}"\n"{2} | grep -E "^|$v" -i --color=always;
        ' \
    | cut -z -f 1 -d $'\t' | tr -d '\n' | xargs -r --null sh -c 'nohup "$0" "$@" >/dev/null 2>&1 &' "$open"
}
```
