### ISSUE TITLE
How to install it in modern go? 

### ISSUE THREAD

**Issue by VolkovIlia** [bellecp/fast-p#19]
Go get depressed, go install did not install file into path

**Comment by bellecp** [comment]
I am not sure what you mean by depressed here. Can you clarify?

**Comment by prosoitos** [comment]
```
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

**Comment by bellecp** [comment]
``go install github.com/bellecp/fast-p@v0.2.5`` appears to be the new way to achieve the former behavior of ``go get`` as per https://go.dev/doc/go-get-install-deprecation.

@prosoitos or @VolkovIlia can you kindly confirm? If that sounds good to you I will update the readme. Thanks for raising the issue,

**Comment by prosoitos** [comment]
This works.

Thank you!

**Comment by bellecp** [comment]
Thanks. Closing this then.

https://github.com/bellecp/fast-p/commit/762d856f328c7070d4eddfa47fa7802f97542ec5
