### ISSUE TITLE
Possible extension by rga

### ISSUE THREAD

**Issue by mizhozan** [bellecp/fast-p#20]
Is it possible to integrate [rga](https://github.com/phiresky/ripgrep-all) so:
  1) improve the speed (even without cache) and 
  2) extend the functionality beyond PDF?

**Comment by bellecp** [comment]
The source of the speed differences is unclear. This project uses boldb while rga uses lmdb, but those two caching databases have very similar designs: https://github.com/boltdb/bolt#lmdb .

I agree that rga feels faster in some instances, and it seems possible to implement a custom adapter for rga that only looks at the first page of the PDF. But currently there seems no documentation for this: https://github.com/phiresky/ripgrep-all/blob/master/doc/Custom%20adapters.md is a work in progress.

I suggest we re-open this when custom adapters in RGA are documented.

**Comment by SuperCowProducts** [comment]
> The source of the speed differences is unclear. This project uses boldb while rga uses lmdb, but those two caching databases have very similar designs: https://github.com/boltdb/bolt#lmdb .
> 
> I agree that rga feels faster in some instances, and it seems possible to implement a custom adapter for rga that only looks at the first page of the PDF. But currently there seems no documentation for this: https://github.com/phiresky/ripgrep-all/blob/master/doc/Custom%20adapters.md is a work in progress.
> 
> I suggest we re-open this when custom adapters in RGA are documented.

@bellecp  [Custom adapters have come](https://github.com/bellecp/fast-p/issues/22#issuecomment-4699282504)!

I was looking to have an `rga`-like tool for PDFs that did fuzzy-search like `fzf` (e.g. a 'semantic' search that detected when 2 terms were in the same paragraph or similar rather than exact matches), maybe this would help?
