### ISSUE TITLE
Page limit

### ISSUE THREAD

**Issue by tmcnitt** [bellecp/fast-p#21]
The line [here](https://github.com/bellecp/fast-p/blob/master/main.go#L131) makes pdftotext stop scanning on page 2 of each pdf. Is there a reason for that? I have some really long PDFs I would like to parse

**Comment by ayoubelmhamdi** [comment]
perhaps it's should be passed the number of scanned pages as an argument, but it's not easy because, for any change of the value of a page passed, the database will be damage

**Comment by bellecp** [comment]
It is on purpose to limit the number of pages. All the content of the first page is passed to fzf, which typically expects single lines. 
The major application of this is to find academic PDFs where title/authors are displayed on the first page.

For finding text in really long pdf, I recommend rga <https://github.com/phiresky/ripgrep-all> with its fzf integration.
