### ISSUE TITLE
macos install [zsh]

### ISSUE THREAD

**Issue by Halem998** [bellecp/fast-p#25]
when trying to install via homebrew, the fan kicked in real hard.
I checked the CPU and my computer almost exploded. Havent experienced before when installing programs.

<img width="1238" alt="Screenshot 2023-07-11 at 20 37 00" src="https://github.com/bellecp/fast-p/assets/69585777/5ec5e2da-25d4-4742-a741-03af0e1e1b1b">

Initially I got a warning that I'm on Catalina and I might run into problems (e.g. slow processing or sth like that)

On my screenshot, it says  `./make.bash`, that was the part where it got really loud and kept hanging there.
Anyways. I have the Zshell and not bash.

So I'm not sure what exactly I'm doing wrong. 
Would appreciate any hint. Thanks

**Comment by bellecp** [comment]
It will be hard to replicate here as I am not currently using MacOS. I suggest running the install command inside a bash shell. Just running ``bash`` from your zsh should give you a regular bash shell from which you can run the install command using homebrew. Hope this helps.

**Comment by Halem998** [comment]
I think it's not about the shell. 
the CPU got up again [this time with bash].
it's been going for half an hour now. 
But it installed not even a quarter of the dependencies ... very weird.
I'm scared I'll trash my device

cmake alone took 21 minutes to complete...

**Comment by bellecp** [comment]
The issue happens while installing grep. I suggest you first solve this step separately by making sure the grep homebrew formula installs satisfactorily.

**Comment by Halem998** [comment]
all good! its up and running. this thing is a BIG productivity boost :)) thanks.
