### ISSUE TITLE
bash only?

### ISSUE THREAD

**Issue by Halem998** [bellecp/fast-p#26]
I put the mentioned code snippet into my .bashrc
but in fact my default shell is zsh [...]
In order to make the `p` command work, i have to instantiate a bash session.

how can I get all this going in Zsh as well?

Thanks alot

**Comment by bellecp** [comment]
I do not use zsh and would not be able to come up with a working solution. If you or someone else has a working code for zsh, please write it here and I will add it to the README. A simple starting point is the code
```
ag -U -g ".pdf$" | fast-p | fzf --read0 --reverse -e -d $'\t'  --preview 'echo -e {1}; echo -e {2}'.
```

**Comment by tjallemaal** [comment]
credit to chatGPT. 


here's the code snippet for my `zshrc`

```p () {
    local open
    open=open   # on OSX, "open" opens a pdf in preview
    ag -U -g ".pdf$" | fast-p | fzf --read0 --reverse -e -d $'\t' --preview 'echo -e {1}; echo -e {2}' | awk -F'\t' '{print $1}' | tr -d '\n' | xargs -r -0 $open > /dev/null 2> /dev/null
}
```

**Comment by bellecp** [comment]
Good to hear it worked out. Your code is missing highlighting of the search query terms in the preview window compared to the bash version.  This is what
```
v=$(echo {q} | tr " " "|"); 
echo -e {1}"\n"{2} | grep -E "^|$v" -i --color=always
```
in the bash snippet from the README is about.

**Comment by tjallemaal** [comment]
Look, I can barely spell my name xD

But somehow there is still highlighting, even without the mention lines ..

**Comment by Halem998** [comment]
I actually forgot to source it the very first time I put your snippet into zsh. 
It worked all along!
