### ISSUE TITLE
"go: finding module ... go: found "  trouble installing on arch

### ISSUE THREAD

**Issue by Halem998** [bellecp/fast-p#27]
I recently installed your super fun code. 
Now I'm trying to get it on my other computer.
Alas, I have no experience with installing packages with go.
I get weird behaviour. 

After the command `go install github.com/bellecp/fast-p@v0.2.5 ` I get " finding .. found"  but I don't think anything happens really. Could you perhaps provide a hint what I could do differently?

![pic-selected-230715-0632-34](https://github.com/bellecp/fast-p/assets/69585777/82c1c2dd-af1a-4737-8170-605da47da717)
![pic-selected-230715-0632-14](https://github.com/bellecp/fast-p/assets/69585777/a502b3d2-f56e-47de-b8b6-26ccbef8c88b)

I checked both directories but there aren't any ` fast-p` binaries ...

I actually tried also doing it manually but I'm just an illiterate and couldnt get it running that way either ...

**Comment by bellecp** [comment]
You would need to study where does ``go install`` place binaries in your system. This is not a question or problem specific to this repository.

You may start investigating with the command ``go env`` that may give you a line ``GOPATH=``. The directory after ``GOPATH=`` may have a ``bin`` subfolder with what you want.

**Comment by Halem998** [comment]
Thank you so much. It worked! Thanks again
