### ISSUE TITLE
PDF preview in both preview window and the search window

### ISSUE THREAD

**Issue by jojowakaki** [bellecp/fast-p#28]
While using the p() function to search for pdf, the search window displays only one result at a time and displays the whole document instead of appearing as one liner. 

fzf version: 0.53.0 (c4a9ccd6)
fast-p version: 0.2.5

code used in .bashrc
```
p () {
    open=xdg-open   # this will open pdf file withthe default PDF viewer on KDE, xfce, LXDE and perhaps on other desktops.

    ag -U -g ".pdf$" \
    | fast-p \
    | fzf --read0 --reverse -e -d $'\t'  \
        --preview-window down:80% --preview '
            v=$(echo {q} | tr " " "|"); 
            echo -e {1}"\n"{2} | grep -E "^|$v" -i --color=always;
        ' \
    | cut -z -f 1 -d $'\t' | tr -d '\n' | xargs -r --null $open > /dev/null 2> /dev/null
}
```

![Screenshot-2024-06-11_17 25 52](https://github.com/bellecp/fast-p/assets/73982843/12dcfdd3-4a19-4e8a-8e0d-e123e942cbd1)

Using the old historical bash code as seen [here](https://raw.githubusercontent.com/bellecp/fast-p/master/p), correct behaviour is still retained. List of files is presented as one line for each possible file. 

![Screenshot-2024-06-11_17 22 02](https://github.com/bellecp/fast-p/assets/73982843/05b9ac74-4cd8-46a7-a74f-04e1ae0bf9ef)

**Comment by bellecp** [comment]
This appears to be a new feature of fzf to support multi-line items in the results. Could you try with the extra option
```
--no-multi-line
```
https://junegunn.github.io/fzf/reference/#--no-multi-line

**Comment by jojowakaki** [comment]
It works as intended with 
`--no-multi-line`
