### ISSUE TITLE
Script doesn't show any pdfs

### ISSUE THREAD

**Issue by kxk** [bellecp/fast-p#4]
Finished all the steps, trying it in a folder with numerous pdf files, but I the script returns:

```
1/1

grep: empty (sub)expression
```

**Comment by bellecp** [comment]
What OS are you using? It is possible that bash and/or grep implementations on MacOS behave differently.

**Comment by kxk** [comment]
I am indeed on a macOS High Sierra (v10.13.6).

**Comment by bellecp** [comment]
See the discussion at the end of https://github.com/bellecp/fast-p/issues/2 ; I close this since it seems to be the same error and same OS.

**Comment by sandrolemosmachado** [comment]
Script is passing the line content and not the file name/address to open command.  Using Ubuntu 18.04
