### ISSUE TITLE
When exiting without opening; terminal is not clean

### ISSUE THREAD

**Issue by raivivek** [bellecp/fast-p#6]
Hi, when I exit from `fast-p` using Ctrl+C or Esc, the terminal leaves debug/help message from the `open` command. I am using the x86_64 MacOS binary.

How to reproduce:

1. Run `p`
2. Exit using Ctrl+C

**Comment by bellecp** [comment]
Can you confirm that adding the flag -r to the xargs command as in https://gist.github.com/bellecp/3988323c4cbfdfdce4eaf2121b4dfa67/revisions#diff-85cf9b51417c7cfb8766aa6b56f7edb9 does fix the issue?

**Comment by raivivek** [comment]
Indeed it does!

Thanks!

--
https://raivivek.in
