### ISSUE TITLE
mac os x - cut binary doesn't support -z option.

### ISSUE THREAD

**Issue by ipstone** [bellecp/fast-p#7]
I tried to solve it by `brew install coreutils`; and then using gcut, instead of cut in the function p definition. 

However, the pdf reader wasn't launched. Might somewhere in the last line is wrong:
| gcut -z -f 1 -d $'\t' | tr -d '\n' | xargs -r --null $open > /dev/null 2> /dev/null

Thank you for this fascinating tool!

**Comment by ipstone** [comment]
I have replaced the last line with: `    | gcut -z -f 1 -d $'\t' | tr -d '\n' | xargs -I F $open "F" `
now it works on mac. I think it's the xargs on mac doens't have gnu extension supports.

**Comment by diego898** [comment]
@bellecp Your suggested fix worked for me

**Comment by bellecp** [comment]
The main README now instructs to use gxargs, gcut, gtr, ggrep to avoid the different behavior of the built-in command in OSX. Also, I am considering a homebrew formula to ease installation, any feedback welcome https://github.com/bellecp/fast-p/issues/11

**Comment by radusuciu** [comment]
Same issue with cut..

```bash
$ cut --version
cut (GNU coreutils) 8.21
```

**Comment by bellecp** [comment]
@radusuciu one option would be to compile a more recent version of coreutils, cf. https://askubuntu.com/questions/736569/how-to-upgrade-coreutils-from-8-21-to-8-24-in-linux-ubuntu-14-04?rq=1

Another option is to change the bash code after the cut command; its only goal is to retrieve the filepath which is everything returned by fzf until the first tab ("\t") character.
