### ISSUE TITLE
[Warning] dpkg: warning missing maintainer

### ISSUE THREAD

**Issue by shubhams** [bellecp/fast-p#9]
I have installed `fast-p` from the precompiled binary [fast-p_0.1.7_linux_amd64.deb](https://github.com/bellecp/fast-p/releases/download/v0.1.7/fast-p_0.1.7_linux_amd64.deb) for Ubuntu 18.04. Everything works fine but when I run:
`$ sudo apt update
`
or 
`$ sudo apt upgrade`
I get a warning saying:
```
dpkg: warning: parsing file '/var/lib/dpkg/status' near line <line-number> package 'fast-p':
 missing maintainer
```
I think this warning would go away if the package maintainer is adding in the precompiled binary.

Output of `$ uname -a`:
```
Linux shubham-Z510 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Output of `$ lsb_release -a`:
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

**Comment by bellecp** [comment]
Last build (v0.1.8) https://github.com/bellecp/fast-p/releases should have fixed the warning. Can you confirm?

**Comment by shubhams** [comment]
Yep, I don't see the warning anymore.
Thanks :+1: 
Closing the issue.
